services:
  app:
    image: myrepo/resumetailor:latest
    restart: always
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
      - DB_URL=jdbc:postgresql://db:5432/cvfitai
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=cvfitai
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local


